[package]
name = "silksongtool"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8"
ecb = "0.1.2"
block-padding = "0.4.2"
base64 = "0.22"
cipher = "0.4"   # provides generic traits
pkcs7 = "0.4.1"
serde_json = "1.0.145"

[[bin]]
name = "silksongtool"
path = "main.rs"